name: issue.yml
on:
  issues:
    types: [opened]

jobs:
  comments:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Comment
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        ISSUE_URL: ${{github.event.issue.html_url}}
      run: gh issue comment $ISSUE_URL -b "merci d'avoir signalé cette erreur"


          
