name: CI
on: push

jobs:
    premier-job:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-java@v4
            with:
              distribution: 'jetbrains'
              java-version: '21'
              cache: 'maven'
              cache-dependency-path: 'test_action/pom.xml' # optional
          - name: Build with Maven
            run: mvn -B package --file pom.xml

