name: CI
on: push

jobs:
    premier-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution: 'jetbrains' # See 'Supported distributions' for available options
                  java-version: '21'


            - name: install dependencies
              run: mvn install

            - name: package
              run: mvn clean package

            - run: java ExStudentApplication.java
