name: CI
on: workflow_dispatch

jobs:
    premier-job:
        runs-on: ubuntu-latest
        steps:
            - name: dit bonjour
              run: echo "hello world"

    deuxieme-job:
        runs-on: ubuntu-latest
        needs: premier-job
        steps:
            - name: dit bonjour encore
              run: echo "hello again"          