name: docker.yml
on:
    push:
    workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
      PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: login
        uses: docker/login-action@v3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
      - uses: actions/checkout@v4
      - run: echo $USERNAME/actionimage
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build
        run: docker buildx build --load -t $USERNAME/actionimage .
      - name: push
        run: docker push $USERNAME/actionimage

