name: docker.yml
on:
    push:
    workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
      PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker buildx build --load -t ${{ env.USERNAME }}/gestionstudent .

      - name: Push Docker image
        run: docker push ${{ env.USERNAME }}/gestionstudent
