name: release
on:
  push:
    tags:
      - 'v*'


jobs:
  premier-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: actions/checkout@v4

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-  

      - name: Install dependencies
        run: mvn dependency:resolve

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: uploader l'artefact
        if: success() && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: app-demo.jar
          path: target/*.jar

      - name: creer la release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: target/*.jar

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

